### ISSUE TITLE
호스트 정보수정 요청

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-backend#10]

**Comment by jongchang** [comment]
- 호스트 정보 수정
```PUT /user```
- 호스트 정보 삭제(회원탈퇴)

**Comment by jongchang** [comment]
**네이버 로그인의 경우 **
현재 DB에서 호스트 정보를 삭제(탈퇴) 후 동일한 계정으로 다시 로그인을 시도하면, 페이지에서는 500에러(Interval sever error)가 발생하고 동시에 DB에 계정 정보가 생성됨. 가입이 안된 채 진행한 로그인이기에 에러가 뜨지만, 이 시도로 자동 회원가입이 되었음을 유저에게 알려줄 필요가 있음(에러 후 재로그인하면 로그인됨). auth.service.ts 코드를 수정해서 이걸 좀더 매끄럽게 할 필요.

**Comment by jongchang** [comment]
- auth.service의 로그인 관련 함수에서 findUserByEmail 시 DB에 값을 없을 경우Null처리.
- user create time, user update time 컬럼 추가

**Comment by jongchang** [comment]
- **참고할것!** kakao 계정이 naver.com이나 gmail.com일 경우: db에서 가입여부 및 회원정보를 이메일로 조회하기 때문에 혼선 발생
  ```ex) 만약 kakao 계정이 jungle@gmail.com일 경우,
db에는 구글계정과 카카오계정 중 먼저 가입한 하나의 계정만 들어가고, provider 컬럼 또한 거기로 결정됨.
-> 먼저 구글계정 gmail로 가입하고 카카오로 로그인하면 로그인됨. db에 provider는 처음에 가입했던 google로 되어있음. 카카오로 로그인 후 회원탈퇴를 하면 db에서 해당 계정 정보가 삭제되기에 google로 접속한 계정또한 삭제된 꼴
```

**Comment by jongchang** [comment]
갱신되기 전(이전에 발행된) 토큰도 검증시 유효하다고 인증이 됨 -> 현재 로그인되어 새로발급된 토큰을 갖고있는 계정을 예전 토큰으로 인증받고 회원탈퇴시키기 가능
