### ISSUE TITLE
[BE]게임이 안끝나는 문제 - 동시성 IMDB 락

### ISSUE THREAD

**Issue by jongchang** [Team-def/recre-backend#112]

**Comment by jongchang** [comment]
load_test로 50명 접속 후 전원 처형시

![Image](https://github.com/Team-def/recre-backend/assets/110075512/d77bf0c8-ddd4-4c81-a52b-362f08fb9247)

**Comment by jongchang** [comment]
load_test로 50명 접속 후 전원 골인시


![Image](https://github.com/Team-def/recre-backend/assets/110075512/870f9898-88c3-4a0c-a292-1b042ef3d915)



![Image](https://github.com/Team-def/recre-backend/assets/110075512/57f02a16-c260-4598-9980-bc7c31962e59)

**Comment by jongchang** [comment]
동시성 문제 + 로컬 환경상 지연문제

**Comment by ChoiWheatley** [comment]
run 이벤트가 async라서 생기는 문제인듯.
