### ISSUE TITLE
중간에 끊긴 소켓 통신에 대한 사용자 식별 및 접속유지 프로토콜 구현

### ISSUE THREAD

**Issue by DongPark987** [Team-def/recre-backend#16]

**Comment by DongPark987** [comment]
socket io 통신에서 네트워크 불안정으로 통신이 끊기는 경우 기존 접속중이던 소켓을 다시 연결시키는 것이 아닌
새로운 소켓을 open 하고 기존 소켓은 폐기되는 동작을 확인.


재접속을 하는 경우 클라이언트에서는 아에 새로운 소켓을 통해 재접속을 시도하며
기존에 사용중이던 소켓은 더이상 컨트롤 하지 않는것으로 확인됨

기존 접속되어있던 소켓은 클라이언트가 더이상 제어하지 않으므로 서버측에서 해당 소켓이 정상적으로
사용중인지 않은지 확인되지 않음 (비정상 접속을 탐지하는 기능이 있는지 조사 필요)

일단 확인된 것으로는 일정 시간이 지날때동안 소켓이 사용되지 않으면 서버측의 socket io  라이브러리
에서 자동으로 타임아웃 기능이 있어 자동 연결 해제를 하는것으로 보임.


(새로고침과 같은 동작은 자동으로 socket io 라이브러리가 소켓을 disconnect 하는 요청을 보내며 통신을 종료함
따라서 위의 네트워크 불안정과 같은 문제와 별개로 처리해야될 필요성이 있어보임)

**Comment by ChoiWheatley** [comment]
[SocketID 고정이 안돼요 uuid 사용해서 플레이어 식별해야해요 (Notion)](https://www.notion.so/recre/SocketID-uuid-f94650e7b77844b28aacc74a8136c298?pvs=4)

**Comment by ChoiWheatley** [comment]
## reopen 사유

호스트가 QR페이지에서 뒤로가기 버튼 눌렀을때 의도와는 다르게 방이 닫혀있지 않은 문제. 그래서 호스트가 방이 있는 상태에서 방을 새로 열었을때 로직이 꼬임

**Comment by ChoiWheatley** [comment]
명시적으로 end_game을 날려
