### ISSUE TITLE
호스트가 그린 그림을 플레이어 클라이언트에서도 볼 수 있게 (+문서화)

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-backend#32]
- api 문서 필요
- 호스트 클라이언트에서 그림판에 그림을 그리면 같은 room에 있는 모든 플레이어 클라이언트들에게 브로드캐스팅이 전송.
- 플레이어 클라이언트의 canvas에 그림을 받아 draw

**Comment by DongPark987** [comment]
호스트 클라이언트
`canvas.addEventListener("mouseup", () => {
        isDrawing = false;
        context.beginPath();
        const canvasData = {
          data: context.getImageData(0, 0, canvas.width, canvas.height).data,
          width: canvas.width,
          height: canvas.height,
        };
        socket.emit('draw', canvasData);
      });
`

플레이어 클라이언트
`
socket.on('draw', (canvasData) => {
        const img = new ImageData(new Uint8ClampedArray(canvasData.data), canvasData.width, canvasData.height);
        context.canvas.width = canvasData.width;
        context.canvas.height = canvasData.height;
        context.putImageData(img, 0, 0);
      });
`

소켓 서버
`  @SubscribeMessage('draw')
  handleDraw(client: any, canvasData: any): void {
    // 클라이언트로 그림 데이터 및 캔버스 정보 전송
    this.server.emit('draw', canvasData);
  }`
  
  위와 같은 코드를 활용하면 호스트가 canvas로 그린 이미지를 플레이어 에게 전송할 수 있음.
