### ISSUE TITLE
캐치마인드 게임종료 api(end_game)에 guard(session guard) 추가

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-backend#38]

**Comment by DongPark987** [comment]
소켓 서버에서 게임 종료 요청 시 호스트가 맞는지 확인하는 데코레이러를 추가했음.
프론트에서 end_game  요청 시 "access_token"을 보내고 있지 않다면 같이 보내도록 수정할 필요가 있음
@poqop721
