### ISSUE TITLE
[BE] 게임 종료 로직

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-backend#66]
어떤 상황에서 서버가 호스트 및 플레이어에게 stop_game을 전송하는지 알아야 함

**Comment by ChoiWheatley** [comment]
참고로, end_game은 호스트가 서버에게 보내는 게임종료 요청

**Comment by jongchang** [comment]
호스트가 end_game시 현재까지의 완주자들은 결산할지, 아니면 진짜 그런거 없이 강제종료할지 선택할 수 있어야 함.함?

**Comment by jongchang** [comment]
플레이어가 비정상적으로 접속종료(ex. 탭끄기) 했을 때 바로 handleDisconnect되는데
이런 경우 current_alive_num-- 고려

**Comment by ChoiWheatley** [comment]
https://github.com/Team-def/recre-backend/issues/74
