### ISSUE TITLE
[BE] typeorm 쿼리 최적화

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-backend#67]
UserInfoService 내에서 불필요한 데이터베이스 조회를 줄인다.

**Comment by DongPark987** [comment]
sessionInfoService를 구현하는데 사용된
typeorm repository 메서드중 불피요한 쿼리를 전송하는 코드를 수정했습니다.

entity 연관관계 맵핑 시 any타입으로 선언해서 사용하던 객체들을 모두 promise 객체 타입으로 수정했습니다.
promise 타입으로 사용함으로 써 sessionInfoService 에서 eager 하게 db에 요청을 보내던 코드를 제거하고
모두 lazy_loading을 하도록 수정했ㅅ브니다.
