### ISSUE TITLE
back에서 player가 ready 한 상태로 게임 시작 준비에 들어갔을 때 레디 취소안되게 'close_gate' 하나 만들어주세요

### ISSUE THREAD

**Issue by poqop721** [Team-def/recre-backend#82]

**Comment by ChoiWheatley** [comment]
`cold_ready`로 이름 바꿔도 좋나요?

**Comment by ChoiWheatley** [comment]
서버는 `close_gate`와 `start_game` 사이의 구간동안 임시로 DB의 플레이어들의 `isAlive` 속성을 False로 만들어놓는다. `start_game` 이벤트가 오면 그때서야 `isAlive` 속성을 다들 True로 만든 뒤에 게임을 시작한다.

**Comment by ChoiWheatley** [comment]
6. 카운트 전에 흔들면 바로 우승자 나오고 끝남 → 위너 없음
7. 게임 시작 후 레디 안풀리게 하는거 처리

**Comment by ChoiWheatley** [comment]
#96 에서 처리함
