### ISSUE TITLE
[BE] RDBMS Unique Constraint Exception을 활용한 동시성 문제 해결

### ISSUE THREAD

**Issue by ChoiWheatley** [Team-def/recre-backend#89]
## README

본 이슈는 한 플레이어의 `ready` 이벤트가 0.01초 안에 두 번 이상 전송할때 발생하는 비동기 관련 버그에 대해서 다룹니다. 예비 **기술적 챌린지** 주제로 활용 가능할 것 같습니다.

**Comment by DongPark987** [comment]
sqlite의 제약조건들을 활용하고 로직의 흐름을 조절해서 문제 해결을 시도하고 있습니다.

**Comment by DongPark987** [comment]
기존 save로 db의 테이블에 새로운 레코드를 생성하던 방식을 사용하면
 이미 존재하는 레코드에 대해 다시 save를 하게 되면 갱신으로 판단되어
 unique 제약이 발생하지 않는것을 확인했습니다.
새로운 레코드를 생성할 때는 insert를 사용하면 unique 제약 발생하는것을
확인헀습니다.
