### ISSUE TITLE
[기술적 챌린지] 분산 부하테스트

### ISSUE THREAD

**Issue by jongchang** [Team-def/recre-backend#90]

**Comment by ChoiWheatley** [comment]
100명 연결이 실제로 가능한지에 대한 증명이 필요. NodeJS 부하 테스트 코드를 바탕으로 진행.

- 랜덤 인터벌로 불규칙하게 run 요청을 보내 좀 더 사실적인 플레이 시뮬레이션을 유도

**Comment by ChoiWheatley** [comment]
<https://github.com/Team-def/load-test> 에서 확인 가능
